### ISSUE TITLE
Question: Is there a method to obtain the height and width of every pixel of a depth map? 

### ISSUE THREAD

**Issue by tgorm1965** [ZumoLabs/zpy#134]
Hi, I would like to obtain this information to accompany the depth maps produced by ZPY. Is this possible using ZPY's implementation? How would I go about this? Thank you!

**Comment by HugoCMU** [comment]
Depth images are single-channel images: same height and width of a normal color image, but 1 channel instead of 3 (RGB). The value of each pixel in a depth image is the distance from that point in 3D space to the camera's position in 3D space. This is usually normalized to [0, 1] before it is used by a ML pipeline. You can turn off this normalization by muting the normalization node in Blender's Compositor Tab:
![image](https://user-images.githubusercontent.com/8493427/124858076-43126480-df62-11eb-8a63-bd8e74bc8c6f.png)

**Comment by tgorm1965** [comment]
Hey Hugo, Right, understood. I understand it would be the same height and width as the RGB image in pixels. But what if I wanted to obtain each pixel's height and width in meters or inches? Would turning off normalisation help in this respect?

**Comment by HugoCMU** [comment]
I suppose you could take the un-normalized value at a pixel to get the distance from the camera to a certain point, and then you could do that for the pixels above/below and left/right to get an estimate for the height and width of that voxel in 3D space. I Is that what you mean by physical size of a pixel?
![image](https://user-images.githubusercontent.com/8493427/124859206-50c8e980-df64-11eb-87d4-0857441b86c9.png)

**Comment by tgorm1965** [comment]
Interesting. Yeah we're trying to see how we can find the real size of an object using pixel width and height but not sure if that's overkill haha

**Comment by HugoCMU** [comment]
Yeah, cameras project out a cone, so the further away an individual depth reading is the larger the area it represents (and thus in a way the uncertainty).

**Comment by tgorm1965** [comment]
Thank you for your help thus far.
