### ISSUE TITLE
Convert COCO annotations .json file to TensorFlow .record file

### ISSUE THREAD

**Issue by franferraz98** [ZumoLabs/zpy#149]
I'm currently trying to train a Tensorflow model using ZPY-generated data. I'm new to both of them, but as far as I know I need a .record file for my training and test sets to be interpreted by the model.

Are there any available scripts that transform ZPY's output into this format? I'm currently only working with bounding boxes and I think I can handle it manually, but soon I'll probably need segmentation images too and that seems a bit more complicated.

Also, I noticed that TensorFlow itself has a 'create_coco_tf_record.py' script, but I haven't been able to get it to work. Is that what you usually use?

Thanks in advance.

**Comment by HugoCMU** [comment]
Unfortunately don't have a script on hand for you since we use PyTorch internally for ML. However, doing some searching on the internets there are a couple different solutions that come up:

- [GitHub repo with some scripts](https://github.com/MetaPeak/tensorflow_object_detection_create_coco_tfrecord)
- [Data annotation website with conversion tools](https://roboflow.com/convert/coco-json-to-tensorflow-tfrecord)
- [Kaggle notebook](https://www.kaggle.com/karthikeyanvijayan/coco-object-detection-dataset-in-tfrecord)

The answer should be somewhere in those sources. Hope this helps!

**Comment by franferraz98** [comment]
In the end I used [this script](https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_coco_tf_record.py) that is included with Tensorflow. It generates a bunch of .record files that you then need to merge, which I did using [this](https://stackoverflow.com/a/58601340). 

Thanks for everything!
